<?php

declare(strict_types=1);

namespace Tourze\GBT4880;

use Tourze\EnumExtra\Itemable;
use Tourze\EnumExtra\ItemTrait;
use Tourze\EnumExtra\Labelable;
use Tourze\EnumExtra\Selectable;
use Tourze\EnumExtra\SelectTrait;

/**
 * GBT 4880.1-2005 语种名称代码第1部分
 *
 * @see https://raw.githubusercontent.com/Recruitee/cadastre/f3c6643fa1fe6deeef0ad49af266f5ab79de7c29/priv/dev/data/languages.json
 * @see https://github.com/Haixing-Hu/typesetting-standard/blob/master/%E8%AF%AD%E7%A7%8D%E5%8F%8A%E6%9C%89%E5%85%B3%E4%BB%A3%E7%A0%81/%E3%80%90GB%3AT%204880.1-2005%E3%80%91%E4%BF%A1%E6%81%AF%E4%B8%8E%E6%96%87%E7%8C%AE%20%E4%B9%A6%E7%9B%AE%E6%95%B0%E6%8D%AE%E5%85%83%E7%9B%AE%E5%BD%95%20%E7%AC%AC1%E9%83%A8%E5%88%86%EF%BC%9A2%E5%AD%97%E6%AF%8D%E4%BB%A3%E7%A0%81.pdf
 */
enum Alpha2Code: string implements Labelable, Itemable, Selectable
{
    use ItemTrait;
    use SelectTrait;

    case Kashmiri = 'ks';
    case Turkmen = 'tk';
    case Uzbek = 'uz';
    case Macedonian = 'mk';
    case Bambara = 'bm';
    case Ukrainian = 'uk';
    case Portuguese = 'pt';
    case Albanian = 'sq';
    case Danish = 'da';
    case Slovenian = 'sl';
    case Luxembourgish = 'lb';
    case Azerbaijani = 'az';
    case Chinese = 'zh';
    case Komi = 'kv';
    case Romanian = 'ro';
    case Norwegian_Bokmal = 'nb';
    case Indonesian = 'id';
    case Kuanyama = 'kj';
    case Cree = 'cr';
    case Western_Frisian = 'fy';
    case Irish = 'ga';
    case Croatian = 'hr';
    case Faroese = 'fo';
    case Esperanto = 'eo';
    case Kannada = 'kn';
    case Oromo = 'om';
    case Fijian = 'fj';
    case Ndonga = 'ng';
    case Lingala = 'ln';
    case Sardinian = 'sc';
    case Zhuang = 'za';
    case Telugu = 'te';
    case Twi = 'tw';
    case Bulgarian = 'bg';
    case Samoan = 'sm';
    case Avaric = 'av';
    case Persian = 'fa';
    case Haitian_Creole = 'ht';
    case Icelandic = 'is';
    case Hausa = 'ha';
    case Maltese = 'mt';
    case Tsonga = 'ts';
    case Tamil = 'ta';
    case Odia = 'or';
    case Kalaallisut = 'kl';
    case Somali = 'so';
    case Tigrinya = 'ti';
    case Nepali = 'ne';
    case Montenegrin = 'cnr';
    case Serbian = 'sr';
    case Urdu = 'ur';
    case Welsh = 'cy';
    case Malayalam = 'ml';
    case Aragonese = 'an';
    case Occitan = 'oc';
    case Igbo = 'ig';
    case Uyghur = 'ug';
    case Aymara = 'ay';
    case Bosnian = 'bs';
    case Gujarati = 'gu';
    case Hiri_Motu = 'ho';
    case Luba_Katanga = 'lu';
    case North_Ndebele = 'nd';
    case Kongo = 'kg';
    case Norwegian = 'no';
    case Javanese = 'jv';
    case Belarusian = 'be';
    case Assamese = 'as';
    case Inupiaq = 'ik';
    case Basque = 'eu';
    case Kinyarwanda = 'rw';
    case Chamorro = 'ch';
    case Russian = 'ru';
    case Inuktitut = 'iu';
    case Sundanese = 'su';
    case Marshallese = 'mh';
    case Tongan = 'to';
    case Czech = 'cs';
    case Armenian = 'hy';
    case Tagalog = 'tl';
    case Korean = 'ko';
    case South_Ndebele = 'nr';
    case Tatar = 'tt';
    case Southern_Sotho = 'st';
    case Avestan = 'ae';
    case Interlingua = 'ia';
    case Tajik = 'tg';
    case Guarani = 'gn';
    case Bashkir = 'ba';
    case Burmese = 'my';
    case Breton = 'br';
    case Hebrew = 'he';
    case Dutch = 'nl';
    case Kurdish = 'ku';
    case Yoruba = 'yo';
    case Catalan = 'ca';
    case Kanuri = 'kr';
    case Xhosa = 'xh';
    case Khmer = 'km';
    case Afar = 'aa';
    case Navajo = 'nv';
    case Manx = 'gv';
    case Abkhazian = 'ab';
    case Sinhala = 'si';
    case Ganda = 'lg';
    case Nyanja = 'ny';
    case Maori = 'mi';
    case Mongolian = 'mn';
    case Chuvash = 'cv';
    case Italian = 'it';
    case Arabic = 'ar';
    case Chechen = 'ce';
    case Kazakh = 'kk';
    case Hungarian = 'hu';
    case Shona = 'sn';
    case Malagasy = 'mg';
    case Ewe = 'ee';
    case Marathi = 'mr';
    case Bangla = 'bn';
    case Fulah = 'ff';
    case Kikuyu = 'ki';
    case Corsican = 'co';
    case Swati = 'ss';
    case Japanese = 'ja';
    case Swedish = 'sv';
    case Herero = 'hz';
    case Afrikaans = 'af';
    case Galician = 'gl';
    case Greek = 'el';
    case Tswana = 'tn';
    case Norwegian_Nynorsk = 'nn';
    case Pashto = 'ps';
    case Tibetan = 'bo';
    case Zulu = 'zu';
    case Estonian = 'et';
    case Rundi = 'rn';
    case Divehi = 'dv';
    case Venda = 've';
    case Cornish = 'kw';
    case Romansh = 'rm';
    case Hindi = 'hi';
    case Tahitian = 'ty';
    case Scottish_Gaelic = 'gd';
    case Thai = 'th';
    case Dzongkha = 'dz';
    case Latin = 'la';
    case Ossetic = 'os';
    case Ojibwa = 'oj';
    case Slovak = 'sk';
    case Swahili = 'sw';
    case Walloon = 'wa';
    case Lao = 'lo';
    case Turkish = 'tr';
    case Sango = 'sg';
    case Akan = 'ak';
    case Spanish = 'es';
    case Kyrgyz = 'ky';
    case Wolof = 'wo';
    case Sanskrit = 'sa';
    case Quechua = 'qu';
    case Finnish = 'fi';
    case Georgian = 'ka';
    case Malay = 'ms';
    case English = 'en';
    case Sichuan_Yi = 'ii';
    case Vietnamese = 'vi';
    case Amharic = 'am';
    case Bislama = 'bi';
    case French = 'fr';
    case German = 'de';
    case Limburgish = 'li';
    case Punjabi = 'pa';
    case Lithuanian = 'lt';
    case Yiddish = 'yi';
    case Polish = 'pl';
    case Northern_Sami = 'se';
    case Nauru = 'na';
    case Sindhi = 'sd';
    case Latvian = 'lv';

    public function getLabel(): string
    {
        return match ($this) {
            self::Kashmiri => '克什米尔语',
            self::Turkmen => '土库曼语',
            self::Uzbek => '乌兹别克语',
            self::Macedonian => '马其顿语',
            self::Bambara => '班巴拉语',
            self::Ukrainian => '乌克兰语',
            self::Portuguese => '葡萄牙语',
            self::Albanian => '阿尔巴尼亚语',
            self::Danish => '丹麦语',
            self::Slovenian => '斯洛文尼亚语',
            self::Luxembourgish => '卢森堡语',
            self::Azerbaijani => '阿塞拜疆语',
            self::Chinese => '汉语',
            self::Komi => '科米语',
            self::Romanian => '罗马尼亚语',
            self::Norwegian_Bokmal => '挪威布克莫尔语',
            self::Indonesian => '印尼语',
            self::Kuanyama => '宽亚玛语',
            self::Cree => '克里语',
            self::Western_Frisian => '弗里西亚语',
            self::Irish => '爱尔兰语',
            self::Croatian => '克罗地亚语',
            self::Faroese => '法罗语',
            self::Esperanto => '世界语',
            self::Kannada => '卡纳达语',
            self::Oromo => '奥洛莫语',
            self::Fijian => '斐济语',
            self::Ndonga => '恩敦加语',
            self::Lingala => '林加拉语',
            self::Sardinian => '撒丁语',
            self::Zhuang => '壮语',
            self::Telugu => '泰卢固语',
            self::Twi => '特威语',
            self::Bulgarian => '保加利亚语',
            self::Samoan => '萨摩亚语',
            self::Avaric => '阿瓦尔语',
            self::Persian => '波斯语',
            self::Haitian_Creole => '海地克里奥尔语',
            self::Icelandic => '冰岛语',
            self::Hausa => '豪萨语',
            self::Maltese => '马耳他语',
            self::Tsonga => '宗加语',
            self::Tamil => '泰米尔语',
            self::Odia => '奥利亚语',
            self::Kalaallisut => '格陵兰语',
            self::Somali => '索马里语',
            self::Tigrinya => '提格雷尼亚语',
            self::Nepali => '尼泊尔语',
            self::Montenegrin => '黑山语',
            self::Serbian => '塞尔维亚语',
            self::Urdu => '乌尔都语',
            self::Welsh => '威尔士语',
            self::Malayalam => '马拉雅拉姆语',
            self::Aragonese => '阿拉贡语',
            self::Occitan => '奥克语',
            self::Igbo => '伊博语',
            self::Uyghur => '维吾尔语',
            self::Aymara => '艾马拉语',
            self::Bosnian => '波斯尼亚语',
            self::Gujarati => '古吉拉特语',
            self::Hiri_Motu => '希里莫图语',
            self::Luba_Katanga => '卢巴-加丹加语',
            self::North_Ndebele => '北恩德贝勒语',
            self::Kongo => '刚果语',
            self::Norwegian => '书面挪威语',
            self::Javanese => '爪哇语',
            self::Belarusian => '白俄罗斯语',
            self::Assamese => '阿萨姆语',
            self::Inupiaq => '依努庇克语',
            self::Basque => '巴斯克语',
            self::Kinyarwanda => '基尼阿万达语',
            self::Chamorro => '查莫罗语',
            self::Russian => '俄语',
            self::Inuktitut => '伊努伊特语',
            self::Sundanese => '巽他语',
            self::Marshallese => '马绍尔语',
            self::Tongan => '汤加语 (汤加岛)',
            self::Czech => '捷克语',
            self::Armenian => '亚美尼亚语',
            self::Tagalog => '塔加洛语',
            self::Korean => '朝鲜语',
            self::South_Ndebele => '南恩德贝勒语',
            self::Tatar => '塔塔尔语',
            self::Southern_Sotho => '南索托语',
            self::Avestan => '阿维斯陀语',
            self::Interlingua => '拉丁国际语',
            self::Tajik => '塔吉克语',
            self::Guarani => '瓜拉尼语',
            self::Bashkir => '巴什基尔语',
            self::Burmese => '缅甸语',
            self::Breton => '布里多尼语',
            self::Hebrew => '希伯来语',
            self::Dutch => '荷兰语',
            self::Kurdish => '库尔德语',
            self::Yoruba => '约鲁巴语',
            self::Catalan => '加泰罗尼亚语',
            self::Kanuri => '卡努里语',
            self::Xhosa => '科萨语',
            self::Khmer => '高棉语',
            self::Afar => '阿法尔语',
            self::Navajo => '纳瓦霍语',
            self::Manx => '马恩岛语',
            self::Abkhazian => '阿布哈兹语',
            self::Sinhala => '僧加罗语',
            self::Ganda => '干达语',
            self::Nyanja => '尼扬贾语',
            self::Maori => '毛利语',
            self::Mongolian => '蒙古语',
            self::Chuvash => '楚瓦什语',
            self::Italian => '意大利语',
            self::Arabic => '阿拉伯语',
            self::Chechen => '车臣语',
            self::Kazakh => '哈萨克语',
            self::Hungarian => '匈牙利语',
            self::Shona => '绍纳语',
            self::Malagasy => '马达加斯加语',
            self::Ewe => '埃维语',
            self::Marathi => '马拉提语',
            self::Bangla => '孟加拉语',
            self::Fulah => '富拉语',
            self::Kikuyu => '基库尤语',
            self::Corsican => '科西嘉语',
            self::Swati => '斯瓦特语',
            self::Japanese => '日语',
            self::Swedish => '瑞典语',
            self::Herero => '赫雷罗语',
            self::Afrikaans => '南非荷兰语',
            self::Galician => '加利西亚语',
            self::Greek => '现代希腊语',
            self::Tswana => '塞茨瓦纳语',
            self::Norwegian_Nynorsk => '新挪威语',
            self::Pashto => '普什图语',
            self::Tibetan => '藏语',
            self::Zulu => '祖鲁语',
            self::Estonian => '爱沙尼亚语',
            self::Rundi => '基隆迪语',
            self::Divehi => '迪维希语',
            self::Venda => '文达语',
            self::Cornish => '康沃尔语',
            self::Romansh => '利托-罗曼语',
            self::Hindi => '印地语',
            self::Tahitian => '塔希提语',
            self::Scottish_Gaelic => '苏格兰盖尔语',
            self::Thai => '泰语',
            self::Dzongkha => '不丹语',
            self::Latin => '拉丁语',
            self::Ossetic => '奥塞梯语',
            self::Ojibwa => '奥杰布瓦语',
            self::Slovak => '斯洛伐克语',
            self::Swahili => '斯瓦希里语',
            self::Walloon => '沃伦语',
            self::Lao => '老挝语',
            self::Turkish => '土耳其语',
            self::Sango => '桑戈语',
            self::Akan => '阿坎语',
            self::Spanish => '西班牙语',
            self::Kyrgyz => '吉尔吉斯语',
            self::Wolof => '沃洛夫语',
            self::Sanskrit => '梵语',
            self::Quechua => '凯楚亚语',
            self::Finnish => '芬兰语',
            self::Georgian => '格鲁吉亚语',
            self::Malay => '马来语',
            self::English => '英语',
            self::Sichuan_Yi => '四川彝语',
            self::Vietnamese => '越南语',
            self::Amharic => '阿姆哈拉语',
            self::Bislama => '比斯拉玛语',
            self::French => '法语',
            self::German => '德语',
            self::Limburgish => '林堡语',
            self::Punjabi => '旁遮普语',
            self::Lithuanian => '立陶宛语',
            self::Yiddish => '依地语',
            self::Polish => '波兰语',
            self::Northern_Sami => '北萨莫斯语',
            self::Nauru => '瑙鲁语',
            self::Sindhi => '信德语',
            self::Latvian => '拉脱维亚语',
        };
    }
}
